### ISSUE TITLE
Consumable data feed (RSS)

### ISSUE THREAD

**Issue by jonnymets** [livgust/macovidvaccines.com#103]
Hi there. First of all, this is just amazing. Fantastic work to all contributors. 

Seems like this repo, being more of the "view", would be valuable to have a ".rss" or ".atom" output capability. These standardized feed formats are not as popular anymore but could be a great way to facilitate people setting up alerts for new appointments and being more proactively aware of changes in the data.

**Comment by jhalexand** [comment]
The RSS format do tend to imply a blog-like update style and may not be the most appropriate for this. A json file updated periodically would accomplish this perhaps more idiomatically. If I were putting myself in the maintainers' shoes, this would make it easier for other sites to syndicate the data in a potentially less free/open way (or with the intention of collecting personal data for advertisers/spammers) but the site infrastructure is pretty easy to deploy anyway, so it wouldn't be so hard for them to just collect it themselves. A json file distributed here takes extra load off the sites themselves, and that is no doubt a Good Thing.

I'm not familiar with Node, but this does have me curious. Soon as I have a chance, I'll take a poke through the source and see how easy this would be. If I can pick up enough of the Node mojo and the maintainers are interested, I could try to patch something together. I suspect the data must already exist in one place post-crawl, so hopefully not hard to coalesce it into a json file.

**Comment by harcod** [comment]
Our front-end is the consumer of a json file created by our back-end.  We access it at:

https://mzqsa4noec.execute-api.us-east-1.amazonaws.com/prod

**Comment by jhalexand** [comment]
Thank you!  This is really only for the unix-shell-savvy at the moment, but I put together a simple project based on this that monitors your data and can invoke a script with the intention of sending a personal notification when there are changes. I put together some sample scripts for sending an email (or email to text), sending a push notification, or popping up a notification on your desktop (on MacOS).  Really appreciate you sharing this data! https://github.com/jhalexand/VaccineSentinelMA/
