### ISSUE TITLE
Eligibility Section UX enhancements

### ISSUE THREAD

**Issue by tkjones117** [livgust/macovidvaccines.com#108]
See comments from Slack: https://macovidvaccines.slack.com/archives/C01N7C2G2KF/p1614788947077400

- Less space after the “Am I eligible” line — if it’s bold, there doesn’t have to be any extra space.
- Adding “Click each item for more detail” under “Am I eligible”, not bold.
- Less space after the checkmark, the same as if it were a bullet character (one space).
- Change checkmarks to bullet points.

<img width="1266" alt="Screen Shot 2021-03-03 at 1 08 44 PM" src="https://user-images.githubusercontent.com/10677676/109851895-31baf380-7c22-11eb-9c39-d9b178a1c9cf.png">

**Comment by harcod** [comment]
Additional Comments on the eligibility UI from Slack

- I’d tighten up the space between the people bullet and the text by half.
- In the Before image that came in email, the header (“Am I eligible to be vaccinated?“) was on a gray background, which was useful to highlight the header and to show people where to click to close it. Can we do something like that here? Or make it bold when it’s open?

**Also**: While we’re looking at the visual design. Can the outline of those expanding boxes be darker? The contrast with the white background makes it hard to see for people with any visual impairment. In this case, I’m referring to the box around the Eligibility dropdown. The outline around each site’s information has the same problem, but it’s not as important to see (though a black rule between sites would probably be better.)
