### ISSUE TITLE
Out of state zip has unintended behavior

### ISSUE THREAD

**Issue by livgust** [livgust/macovidvaccines.com#118]
Replication steps:
- enter zip in Massachusetts
- notice mile distance appears
- enter zip out of state (like 12345, which is in Schenectady)
- notice same milage appears as with MA zip

**Comment by harcod** [comment]
**Reason**: `us-Zips` is not returning coordinates for 12345.

**Comment by harcod** [comment]
Local test case: **02634** (Centerville, MA) is a ZIP Code for PO Boxes and thus not in the ZCTAs from the Census.  Here is a [list of ZIP Codes for Centerville](https://www.zip-codes.com/city/ma-centerville.asp). Note that 02634 is a zero population area of PO Boxes.

Looks like we might need another way to get this information.
