### ISSUE TITLE
Filter UX Changes

### ISSUE THREAD

**Issue by harcod** [livgust/macovidvaccines.com#157]
This issue came from the [#UX Channel on Slack](https://macovidvaccines.slack.com/archives/C01N7C2G2KF/p1615414245170700?thread_ts=1615215597.119200&cid=C01N7C2G2KF)

1. For the helper text (“Enter a ZIP Code in Massachusetts.“) and box outline, can we use red instead of the orangey color? Red’s just more typical. The red of the radio buttons is good. (And I do like how you detect out-of-state ZIP Codes so quickly.)

2. Spacing changes.
- Add space between the left edge of the window and the ZIP Code box, I added five pixels.
- Remove space on the right side of the box. I brought it in so there’s a comfortable margin after the checkbox text, about the same as on the left of the checkbox.
- Add space on the inside left edge of the ZIP Code box. I added five pixels.
- Remove space on the inside right side of the ZIP Code box. I cut it down to make a comfortable margin next to “25”. But looking at it, it should be the same as the left margin (I can fix that later if you want).
- Add space under the label “ZIP Code:“. Again, I added five pixels.

![image](https://user-images.githubusercontent.com/546007/111790021-290c2380-8898-11eb-9199-ee4f2689c0c2.png)

**Comment by harcod** [comment]
Per #ux channel... please change RadiusFilter to use [ **Any, 10, 25, 50** ]

**Comment by AnthonySalmeron** [comment]
I removed padding from the left but didn't completely make it match how much padding was on the right because the "Clear Filters" button then extends beyond where the box is. I can reduce it more if we want.
<img width="306" alt="Screen Shot 2021-03-31 at 7 39 49 PM" src="https://user-images.githubusercontent.com/55327777/113225481-c0d81d00-925b-11eb-9633-577776b5a3dc.png">

**Comment by harcod** [comment]
Please post a screen shots to the [Slack #ux channel](https://macovidvaccines.slack.com/archives/C01N7C2G2KF) for visual reviews.

**Comment by hshubin** [comment]
Looks good, thanks.

**Comment by harcod** [comment]
Fixed by https://github.com/livgust/macovidvaccines.com/pull/167
