### ISSUE TITLE
Add CONTRIBUTING.md

### ISSUE THREAD

**Issue by MattRC7** [livgust/macovidvaccines.com#16]
It could be helpful, as the project matures, to include a markdown file that describes how people can contribute. I found [a nifty guide](https://opensource.guide/starting-a-project/#your-pre-launch-checklist) here. For now, it can probably be pretty simple.

**Comment by livgust** [comment]
Thanks! (full disclosure: haven't looked at your link) FYI you may be able to grab some text from our #getting-started channel

**Comment by dgabriel123** [comment]
Hello @MattRC7 @livgust may I work on this issue?
