### ISSUE TITLE
Cosmetic: SIGN UP button lacks top padding in some cases (notably CVS with availability)

### ISSUE THREAD

**Issue by pfurbacher** [livgust/macovidvaccines.com#165]
At the moment, the only sites which exhibit this cosmetic issue are CVS locations which have availability, the amount of which cannot be determined. But I think I have seen this with other sites some days back. (Are there other sites like CVS where we can get a whiff of availability but not the count? These may exhibit the same issue.)

Here's a screen shot which shows the lack of top padding for the SIGN UP button: 

<img width="325" alt="Cosmetic issue-button lacks top padding" src="https://user-images.githubusercontent.com/4611136/112432388-36e9fa80-8d17-11eb-8cc6-3d7f916168ee.png">

**Comment by harcod** [comment]
This was recently changed in PR #155.  The new UI looks like this:

![image](https://user-images.githubusercontent.com/546007/112664937-e5ce2980-8e30-11eb-882e-79883d6b5cff.png)

**Comment by harcod** [comment]
Already address in PR #155
