### ISSUE TITLE
Add a link to the GitHub repo under the "About" tab.

### ISSUE THREAD

**Issue by JasonD94** [livgust/macovidvaccines.com#22]
Most sites that have their source on GitHub usually call that out somewhere. Maybe under the "About" page, add something like:

_Source available on [GitHub](https://github.com/livgust/macovidvaccines.com)._

Could also add it to the footer, depends how much you want to call out the source being available.

**Comment by bernfarr** [comment]
If no-one has tackled this yet, I'll work on it.

**Comment by JasonD94** [comment]
That's a good idea @livgust . I didn't realize there is a Slack, so definitely worth pointing out.

**Comment by bernfarr** [comment]
I'm proposing the following changes, I'll create a pull request shortly
From this:
![AboutBefore](https://user-images.githubusercontent.com/2963762/108508474-df74ec80-7289-11eb-95bf-57ecd90f0215.jpg)

To this:
![AboutAfter](https://user-images.githubusercontent.com/2963762/108508483-e26fdd00-7289-11eb-800e-7a5cfb468302.jpg)

There's other work that should be done here. If we're using Material UI, then we should replace `<p>` and `<a>` tags with links. Also probably improve styling use overall. But that's less important that getting these changes in right now.

**Comment by bernfarr** [comment]
Here's what I'm committing shortly. I've removed the direct link to Slack and replaced it with an email link that adds a subject line of **I want to get involved** and a body of **Here's how I can help...**. I also modified the Give Feedback email link to have a subject line of **Site feedback**.

I know there's a leading underscore in the **email the team** link, can't seem to get rid of that.

<img src="https://user-images.githubusercontent.com/2963762/108601075-b24b3b80-7368-11eb-884d-979d584e66f4.png " width="400">
