### ISSUE TITLE
Consolidate "Am I Eligible to be Vaccinated"

### ISSUE THREAD

**Issue by tkjones117** [livgust/macovidvaccines.com#47]
Now that we're past Feb 18th, we can consolidate the "Am I Eligible to be Vaccinated" into 1 section ("The following groups are currently eligible"). 

This would mean replacing `Individuals age 75+` with `Individuals age 65+`.

**Comment by livgust** [comment]
Suggestion: To reduce # of bullets, consolidate some of the phase I bullet points into a generic "Healthcare workers" one

**Comment by tkjones117** [comment]
Note from Slack: maintain groupings like the MA gov sites do, but you can remove the note about "Feb 18"

**Comment by harcod** [comment]
Proposal screenshot:

![image](https://user-images.githubusercontent.com/546007/108378591-2358ea80-71d3-11eb-8a45-a3fa5d49dd0e.png)

**Comment by harcod** [comment]
Updated version:

![image](https://user-images.githubusercontent.com/546007/108383962-44700a00-71d8-11eb-85d5-7e99718a1135.png)
