### ISSUE TITLE
Update design of residency-restricted locations

### ISSUE THREAD

**Issue by livgust** [livgust/macovidvaccines.com#55]

**Comment by harcod** [comment]
From Daniel Cho (via Slack). UI Suggestion.

**CURRENT**:
![Screen Shot 2021-02-18 at 7 17 55 PM](https://user-images.githubusercontent.com/546007/108521813-1d7a0c80-729a-11eb-9476-ab7412e3e5e3.png)

**PROPOSED**:
![Screen Shot 2021-02-18 at 7 22 38 PM](https://user-images.githubusercontent.com/546007/108522074-67fb8900-729a-11eb-8a7b-3f9e4dddcb13.png)

![Screen Shot 2021-02-18 at 7 18 04 PM](https://user-images.githubusercontent.com/546007/108521685-fae7f380-7299-11eb-9549-c81ead697798.png)

**Comment by johnhawkinson** [comment]
Note that the "current" design is better than so the old screenshot is outdated.
See #49 (merged) which also noted open problems:

> Other changes worth doing but not implemented here would be: 1) tightening up the space after the heading, 2) copying the yellow/amber iconography into the dialog, 3) formatting the OK button with an affordance for clicking. I'm sure someone more experienced in React could do those much faster than I.

Further, the color conversation isn't settled yet, and there's some confusion on color semantics versus accessibility requirments versus Material UI palette. Errors vs. warnings vs. advisories. &c.

**Comment by danieljaecho93** [comment]
Yep, bolding the text definitely was a good choice. This definitely isn't the final iteration, but I think while we try to figure out the best ways to making alerting visitors a cohesive experience (e.g. minimizing the number of clicks to see who's eligible for specific sites), we can stick this modal window for now. Like you mentioned, we don't necessarily need to overemphasize the warning, thus the simple combination of bolded text + clear CTA with the OK button.

**Comment by harcod** [comment]
1st stab...
Color = Red (ff0000)
Button = Theme's primary which is the color of the page header banner.

![image](https://user-images.githubusercontent.com/546007/108553830-39dd6f80-72c1-11eb-9974-2b1cd6e41b07.png)

![image](https://user-images.githubusercontent.com/546007/108553897-4f529980-72c1-11eb-92fc-7b2b987d9d5a.png)

**Comment by livgust** [comment]
I vote to get rid of the quotes! And @harcod in Slack we discussed using theme.palette.error.dark for the color - sorry for the disjointed conversation. We also said we should change the copy to "Important Eligibility Notice" instead of "May be restricted."

For the sites where we say, like "Eligible populations in Lynn and Nahant" we'd leave that copy instead of changing it to "Important Eligibility Notice"

**Comment by harcod** [comment]
![image](https://user-images.githubusercontent.com/546007/108565344-85e4e000-72d2-11eb-80fa-0a1d454fed8d.png)

![image](https://user-images.githubusercontent.com/546007/108565401-9c8b3700-72d2-11eb-96cf-c14752c8c7ff.png)
