### ISSUE TITLE
Only show appointments should not display sites with no sign up link

### ISSUE THREAD

**Issue by harcod** [livgust/macovidvaccines.com#67]
Some sites have listed appointment availability, but provide **no sign up link**.  These sites should not be displayed when we are showing "Only show locations with available appointments" as there is no way for the user to obtain an appointment as far as we can tell.

We currently display this advice when prompted about the lack of a sign up link.  We should keep this message as the location will be displayed with the "Only show available appointments" is _unchecked_.

> We were unable to retrieve a sign-up link for this location. It's likely that this location is pulling from a wait list and is not scheduling any new appointments.

EXAMPLE at MAImmunizations:
![image](https://user-images.githubusercontent.com/546007/108603738-b29f0300-7377-11eb-9510-bfba36ea047f.png)

**Comment by j256** [comment]
I think we should show _something_ or not show it at all.  We must have a link to the site right because we scraped it.
