### ISSUE TITLE
Should show sites if no slots available to make the site look less empty

### ISSUE THREAD

**Issue by j256** [livgust/macovidvaccines.com#74]
When there are no slots available, the site looks really dead.  I think that if we have less than X slots with any data that we should show a bunch of slots that are empty so people feel like they need to come back.  Right now it looks like the site is completely offline or something.  Or maybe some small text like:

"Only X of the Y sites that we are downloading from is presenting any available slots right now.  Please check back later."

![image](https://user-images.githubusercontent.com/1749962/108636921-40e9b680-7456-11eb-81c4-0f72376da836.png)

**Comment by harcod** [comment]
See related issue #72

**Comment by j256** [comment]
Duh. sorry @harcod
