### ISSUE TITLE
Link phase & eligibility information

### ISSUE THREAD

**Issue by livgust** [livgust/macovidvaccines.com#8]
Put phase and eligibility information somewhere easily noticeable. Preferably get it straight from the state's website or link to it so that we don't have to keep it updated manually.

**Comment by jrogers97** [comment]
@livgust it looks like the state website uses this google form inside an iframe to let the user check their eligibility - https://docs.google.com/forms/d/e/1FAIpQLSeOcfCPu_afvFILB_nXZz3v9VMaFZZQMgGbKGiU7o3VBr5m7Q/viewform?embedded=true. 
Maybe a "Check eligibility" button that opens up a dialog with this form embedded?

**Comment by harcod** [comment]
@livgust I think that this issue can be closed by PR #31
