### ISSUE TITLE
UX: Show appointment history to build user confidence

### ISSUE THREAD

**Issue by johnhawkinson** [livgust/macovidvaccines.com#81]
At this morning's standup, Liv noted that she's been getting a lot of site user feedback that whenever they go to the site, they see there are no appointments available, and thus conclude our site is just as bad as Vaxfinder.

The answer of course is that there _were_ appointments available, but they disappeared almost as fast as they are available.

My take on this is that therefore we should endeavor to design the user experience so they know that we _did_ have vaccine appointments yesterday, and some way to show how many. This is with the purpose of building confidence (aka implying that we will have more in the future).

---

There are a lot of different ways to approach that, here are some:

1. When we show a site with no available appointments (or even one with!), give a list of how many historical appointments we knew about. E.g.
  ...
  _Feb 21 previously had 800 appointments here.
  Feb 22 previously had 1,000 appointments here._ 

1. We could try to do that in some way that shows rate (first derivative of appointments) rather than just raw. This might imagine predictions like, "_On the average, one new appointment appears every {10 minutes}._" That could be either on a per-site basis or overall.

1. We can make a change to the No Appointments Available box. Instead of showing complex multivariate data (which I am biased in favor of!), we could show something much simpler: "_In the past 24 hours, we showed 700 appointments available_." with the implication of "Keep checking back for more."

1. We could visualize appointment histories. As I said on the Slack on Friday, "I never would have thought of a map with inline sparkline graphs of availability history for each site, without having seen this (from your link):"
<img width="1142" alt="Screen Shot 2021-02-12 at 15 39 55" src="https://user-images.githubusercontent.com/1270718/108858607-5a0b7800-75ba-11eb-8c50-6a5938f66ff4.png">

--- 
The above list is not intended to be exhaustive, or even suggested.
It can probably be much-improved upon.
Please do so!

**Comment by j256** [comment]
I would think showing the users all of the sites that we scrape would give more assurance.  Seeing a grid like:

| Site | Slots open </br> Last 24 Hours | Last Open Time | Last Checked |
| --- | --------------- | --------------- | ----------------- |
| Gilette | 150 | 4:25 pm | 3 minutes ago |
| Malden CVS | 10 | Yesterday | 1 minute ago |
...

**Comment by jhalexand** [comment]
One thing that might be very helpful (though would also focus demand even more) could be a chart showing, for each category of site (e.g. State-run, CVS, Walgreens, basically one for each scraper type), the time of day that appointments historically become available. Something akin to the histograms that Google shows of "Popular times" when restaurants are the busiest. For example, google for "twyrl arlington" then scroll down to see it in the sidebar on the right. I could also imagine some sort of heatmap-style chart where the X-axis is the hour of the day and the Y-axis is the site type. Sorry that I don't have any experience with Node.

**Comment by ramon-h** [comment]
> At this morning's standup, Liv noted that she's been getting a lot of site user feedback that whenever they go to the site, they see there are no appointments available, and thus conclude our site is just as bad as Vaxfinder.

Given that this is the issue you're trying to solve, the quickest and easiest solution to address that is probably to highlight testimonials from the [GoFundMe campaign](https://www.gofundme.com/f/wwwmacovidvaccinescom?utm_source=customer&utm_medium=copy_link&utm_campaign=p_cf+share-flow-1) on the website. Knowing that the website worked well enough for other people that they were willing to donate their own money is a pretty powerful advocate for the website.

**Comment by livgust** [comment]
This issue is no longer relevant, as availability is up.
