### ISSUE TITLE
Translate the website into other languages

### ISSUE THREAD

**Issue by MattRC7** [livgust/macovidvaccines.com#94]
There are a few components to this:

1. Creating a key-value mapping for each distinct text string in the app.
2. For each language we want to support, adding a value for each key in our mapping (starting with English as a base).
3. Feeding the key-value mappings into a translation framework and rendering them in the app.

For the client-side, [i18next](https://www.i18next.com/) is an industry--standard. Our app would likely want to use [react-i18next](https://react.i18next.com/). For a small app like ours, we can probably get away with a static JSON file containing the keys and translations, and manually updating them via PRs. If the site expands we will want to look into a server-side persistence mechanism, or a service such as [Locize](https://locize.com/).

I can help with setting up the framework, but I won't be very useful as a translator.

**Comment by ramon-h** [comment]
I've used react-i18next before and found it worked well. It'd help clean up the "slot" vs "slots" code too.

**Comment by MattRC7** [comment]
> I've used react-i18next before and found it worked well. It'd help clean up the "slot" vs "slots" code too.

Let me know if you want to team up on this! One thing i'm not sure of is, if we're using a local file instead of a back end like Locize, how do we provide the translators with enough context to properly do their work? I imagine sending them a raw JSON file would be unhelpful.

**Comment by ramon-h** [comment]
Yeah, I may be able to help.

About translators having enough context, I think the UI may be simple enough that they will be able to get most of the context just by loading the website. Since there aren't many pages or a lot of nested UI, it _might_ not be that bad. Also, there seems to be relatively little text anyway since we wouldn't need to translate location names or addresses. If more context was needed, a folder (or separate repo) with screenshots where we label the key names is probably enough.

**Comment by MattRC7** [comment]
> Yeah, I may be able to help.
> 
> About translators having enough context, I think the UI may be simple enough that they will be able to get most of the context just by loading the website. Since there aren't many pages or a lot of nested UI, it _might_ not be that bad. Also, there seems to be relatively little text anyway since we wouldn't need to translate location names or addresses. If more context was needed, a folder (or separate repo) with screenshots where we label the key names is probably enough.

Nice, so they'd just look at screenshots and translate from the English text. And then we would need to take the translations in whatever format they return them to (annotated screenshot? PDF? Spreadsheet/CSV?) and add them to the translation file?
